l_english:
 SETTING_AUTOSAVE_TO_CLOUD: "Автозбереження в хмару"
 SETTING_SAVE_FILE_FORMAT: "Стандартний формат збереження"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Цей параметр замінюється в режимах залізної волі, хмарі і режим розробника"
 OPTION_SAVE_FILE_TEXT: "Текст"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Заархівований текст"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Архівований двійковий файл"
 SETTING_TOOLTIP_MODE: "Режим підказки"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nВиберіть спосіб блокування підказок:\n   #b Наведення мишки#! - блокує, якщо навести вказівником мишки на підказку.\n   #b Часове блокування#! - блокує підказки через певний час.\n   #b Дійове блокування#! - блокує підказки при клаці середньою кнопкою мишки.\n   #b Часове або дійове блокування#! - використовує блокування за часом або за дією"
 SETTING_TOOLTIP_MODE_NO_LOCK: "Без замка"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Наведення миші"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Дійове блокування ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Часове блокування ( Mouse Anchor )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Дійове блокування"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Часове блокування"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Часове або дійове блокування"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nВстановлює затримку до появи підказки під час наведення вказівника на елемент із підказкою."
 SETTING_TOOLTIP_DELAY: "Затримка перед показом"
 SETTING_TOOLTIP_UNLOCK_TIME: "Затримка розблокування"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nВстановлює затримку до розблокування підказок."
 SETTING_TOOLTIP_LOCK_TIME: "Блокування підказок"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nВстановлює затримку перед блокуванням підказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Заблокована затримка відкриття"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nВстановлює затримку перед блокуванням підказок, коли інша підказка вже відкрита."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Просунуті"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Загальні"
 SETTINGS_CATEGORY_SFX: "Звукові ефекти"
 SETTINGS_CATEGORY_MFX: "Музика"
 SETTINGS_CATEGORY_LANGUAGE: "Мова"
 SETTINGS_CATEGORY_SAVE_GAMES: "Збереження гри"
 SETTINGS_CATEGORY_TOOLTIPS: "Параметри підказок"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Керування мапою"
 SETTINGS_CATEGORY_MAPMODES: "Режими мапи"
 SETTING_SHADER_QUALITY: "Якість шейдерів"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T $SETTING_SHADER_QUALITY$#!\nВизначає якість різних шейдерів й ефектів.\n\n#T Висока:#! Покращує якість деяких шейдерних ефектів за рахунок продуктивности.\n\n#T Середня:#! Звичайні налаштування.\n\n#T Низька:#! Цей параметр призначений для компів низького клясу та не рекомендований через втрату візуальної якости. Кілька шейдерів спрощено для підвищення графічної продуктивности."
 SETTING_SHOW_NUDITY: "Показати наготу"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nВстановлює, чи можна показувати наготу."

 SETTING_VALUE_HOURS: "$VALUE|0$ год"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"

 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Цикл дня та ночі"
 SETTING_DAYNIGHT_CYCLE: "Увімкнути цикл дня та ночі"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP:0 "#T $SETTING_DAYNIGHT_CYCLE$#!\nEnables a day and night cycle for the sun movement."
 SETTING_DAYNIGHT_SYSTEMTIME: "Увімкнути синхронізацію з місцевим часом"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSyncronizes the day night cycle speed and time to the computers local time.\n\n#!Will override simulation speed setting."
 SETTING_DAYNIGHT_SPEED: "Швидкість симуляції"
 SETTING_DAYNIGHT_SPEED_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SPEED$#!\nHow fast the time will cycle between day and night.#"
 SETTING_SUN_DURATION: "Сонячні години"
 SETTING_SUN_DURATION_TOOLTIP:0 "#T $SETTING_SUN_DURATION$#!\nThe amount of hours of sun in a day."
 SETTING_SUNRISE_TIME: "Час світанку"
 SETTING_SUNRISE_TIME_TOOLTIP:0 "#T $SETTING_SUNRISE_TIME$#!\nThe hour the sun will rise.\n\n#!Only used when synced with local time. #!"
 SETTING_DAYNIGHT_SET_TIME: "Увімкнути ручний час"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP:0 "#T $SETTING_DAYNIGHT_SET_TIME$#!\nSets time of day to a specified hour.\n\n#!Will override simulation speed and sync local time settings."
 SETTING_SUNRISE_SET_TIME_HOUR: "Ручний час"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP:0 "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nLocks the time to this hour.\n\n#!Only used when manual time is enabled#"

 SETTING_BUILDINGS_CUTOFF: "Відсівання віддалених будівель"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP:1 "#T $SETTING_BUILDINGS_CUTOFF$#!\nShow fewer buildings on the map, the further away they are from the camera.\n\nTurning it on may increase performance."

 SETTINGS_CATEGORY_GAME_PORTRAITS: "Портрети"
 SETTING_SOUNDTRACK: "Музика на тлі"
 SETTING_SOUNDTRACK_TOOLTIP: "Загальна музика на тлі"
 SETTING_MUSIC_STINGERS: "Музичні стинґери"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Короткі музичні фрази для покращення ігрового процесу"

  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Музика"
 SETTING_AMBIENT: "Довкілля"
 SETTING_MUSIC_TOOLTIP: "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_AMBIENT_TOOLTIP: "#T Гучність довкілля\n#!Встановлює гучність довкілля."

 SETTING_MAP_TOOLTIP_DELAY: "Затримка підказки мапи"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nВстановлює затримку перед показом підказки мапи."

 SETTING_MAP_MODE_DELAY: "Затримка режиму мапи"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Затримка перед заміною новим режимом мапи старого"
 SETTING_MAP_MODE_FADE_IN: "Плавне виникнення режиму мапи"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Час появи нового режиму мапи після зникнення старого, у секундах"
 SETTING_MAP_MODE_FADE_OUT: "Плавне зникнення режиму мапи"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Час згасання поточного режиму мапи після його затримки, коли має бути застосований новий режим мапи, у секундах"

 SETTING_OCCUPATION_STRIPES: "Смугаста окупація"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nУвімкнути кольорові смуги як візуальне позначення окупації на мапі замість зображень стягів країн"
 
 SETTING_PORTRAIT_RENDER_SCALE:0 "Portrait Render Scaling"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP:0 "#T SETTING_PORTRAIT_RENDER_SCALE#!\nImprove character portrait detail level by upscaling render results, at the cost of some more rendering performance."
 
 OPTION_PORTRAIT_RENDER_SCALE_NONE:0 "×1.0 - None"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM:0 "×1.5 - Medium"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH:0 "×2.0 - High"

 ui_skin_theme: "Інтерфейс користувача"
 ui_skin_theme_desc: "Кнопки, рамки, вікна, горища тощо у грі."
 papermap_theme: "Паперова мапа"
 papermap_theme_desc: "Цю мапу ви побачите, коли віддалите гру."
 table_top_theme: "Стільниця"
 table_top_theme_desc: "Якщо віддалити настільки, наскільки це можливо, ви побачите цю стільницю вгорі і внизу екрана."
 table_asset_1_theme: "Об’єкт на столі (верхній лівий кут)"
 table_asset_1_theme_desc: "Об’єкт, що відображається у верхньому лівому куті стільниці поруч з мапою при відаленні."
 table_asset_2_theme: "Об’єкт на столі (верхній правий кут)"
 table_asset_2_theme_desc: "Об’єкт, що відображається у верхньому правому куті стільниці поруч з мапою при відаленні."
 table_asset_3_theme: "Об’єкт на столі (нижній лівий кут)"
 table_asset_3_theme_desc: "Об’єкт, що відображається у нижньому лівому куті стільниці поруч з мапою при відаленні."
 table_asset_4_theme: "Об’єкт на столі (нижній лівий кут)"
 table_asset_4_theme_desc: "Об’єкт, що відображається у нижньому правому куті стільниці поруч з мапою при відаленні."
 building_sets_themes: "Набір будівель"

 color_blind_mode_test: "Тест"