l_english:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Через мірування вище $VALUE|%0$ інтерфейс буде поза екраном#!"
 RECOMMENDED_GUI_SCALE: "Через мірування вище $VALUE|%0$ інтерфейс буде поза екраном"
