l_english:
 SETTING_REFRACTION: "Заломлення"
 SETTING_REFRACTION_QUALITY: "Якість заломлення"
 SETTING_MAPOBJECT_QUALITY: "Об'єкти мапи"
 SETTING_MAP_SSAO: "Мапа SSAO"
 SETTING_DOF: "Глибина різкости"
 SETTING_LENS_FLARE: "Відблиск об'єктива"